pgm: 
  image: occupancy_grid.pgm
  resolution: 0.05
  origin: [0.0, 0.0, 0.0]
  occupied_thresh: 0.65
  free_thresh: 0.196
  negate: 0
  unknown: 200
  occupied: 0
  free: 255
  laser_height: 0.7
  map_configuration:
    resolution: 0.05
    origin: [0.0, 0.0, 0.0]
    occupied_thresh: 0.65
    free_thresh: 0.196
    negate: 0
