name: Continuous Integration

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install blender
        run: |
          sudo apt-get update
          sudo apt-get install blender python3-pip python3-venv -y
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Generate composable models
        run: |
          textx generate models/examples/*.floorplan --target json-ld --output-path .
      - name: Generate 3D mesh and occupancy grid
        working-directory: ./src
        run: |
          blender --background --python-use-system-env --python exsce_floorplan/exsce_floorplan.py -- ../models/examples/brsu_building_c_with_doorways.floorplan 
  lint:
    uses: ./.github/workflows/black.yaml